import { useRef, useState } from 'react';
import { buildParticipantCsvTemplate, downloadCsv, parseParticipantCsv } from '../../lib/csv.js';

const STATUS_LABELS = {
  created: { label: 'Created', cls: 'status-pill ok' },
  enrolled_existing: { label: 'Enrolled', cls: 'status-pill ok' },
  already_enrolled: { label: 'Already enrolled', cls: 'status-pill' },
  error: { label: 'Error', cls: 'status-pill warn' },
};

export default function AddSessionParticipants({ onAdd, onCancel }) {
  const [mode, setMode] = useState('direct');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [results, setResults] = useState(null);

  const [username, setUsername] = useState('');
  const [fullName, setFullName] = useState('');

  const [csvRows, setCsvRows] = useState([]);
  const [csvFilename, setCsvFilename] = useState('');
  const [csvParseErrors, setCsvParseErrors] = useState([]);
  const fileInputRef = useRef(null);

  async function submitDirect(e) {
    e.preventDefault();
    setError(''); setResults(null); setBusy(true);
    const trimmed = username.trim();
    const { data, error: err } = await onAdd([{ username: trimmed, full_name: fullName.trim() }]);
    setBusy(false);
    if (err) { setError(err.message); return; }
    setResults(data);
    const created = data?.find(r => r.username === trimmed && r.status === 'created');
    if (created) {
      setUsername(''); setFullName('');
    }
  }

  function onFileChange(e) {
    setCsvRows([]); setCsvParseErrors([]); setCsvFilename(''); setResults(null); setError('');
    const file = e.target.files?.[0];
    if (!file) return;
    setCsvFilename(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      const text = String(reader.result || '');
      const { rows, errors } = parseParticipantCsv(text);
      setCsvRows(rows);
      setCsvParseErrors(errors);
    };
    reader.onerror = () => setError('Could not read the file.');
    reader.readAsText(file);
  }

  async function submitCsv() {
    if (csvRows.length === 0) { setError('Nothing to upload.'); return; }
    setError(''); setResults(null); setBusy(true);
    const { data, error: err } = await onAdd(csvRows);
    setBusy(false);
    if (err) { setError(err.message); return; }
    setResults(data);
    setCsvRows([]); setCsvFilename('');
    if (fileInputRef.current) fileInputRef.current.value = '';
  }

  function downloadTemplate() {
    downloadCsv('participants_template.csv', buildParticipantCsvTemplate());
  }

  return (
    <div className="add-participants-panel">
      <div className="add-participants-tabs">
        <button
          type="button"
          className={`view-tab ${mode === 'direct' ? 'active' : ''}`}
          onClick={() => { setMode('direct'); setResults(null); setError(''); }}
        >
          Add one
        </button>
        <button
          type="button"
          className={`view-tab ${mode === 'upload' ? 'active' : ''}`}
          onClick={() => { setMode('upload'); setResults(null); setError(''); }}
        >
          Upload CSV
        </button>
        <button type="button" className="ghost" onClick={onCancel} style={{ marginLeft: 'auto' }} disabled={busy}>
          Close
        </button>
      </div>

      {mode === 'direct' && (
        <form onSubmit={submitDirect} className="add-person-form" style={{ marginTop: '0.75rem' }}>
          <div className="form-grid">
            <div>
              <label className="form-label">Username</label>
              <input className="form-input" required value={username} onChange={e => setUsername(e.target.value)} placeholder="e.g. jane.doe" />
              <p className="hint">Letters, digits, dot, underscore, hyphen. A temp password is generated automatically.</p>
            </div>
            <div>
              <label className="form-label">Full name</label>
              <input className="form-input" value={fullName} onChange={e => setFullName(e.target.value)} placeholder="Optional" />
            </div>
          </div>
          {error && <p className="error">{error}</p>}
          <div className="form-actions">
            <button type="submit" disabled={busy || !username.trim()}>
              {busy ? 'Adding…' : 'Add to session'}
            </button>
          </div>
        </form>
      )}

      {mode === 'upload' && (
        <div style={{ marginTop: '0.75rem' }}>
          <p className="hint" style={{ marginTop: 0 }}>
            Download the template, fill it in Excel (one participant per row), save as CSV, then upload here.
            Columns: <code>username</code>, <code>full_name</code> (optional). Temp passwords are generated by the server.
          </p>
          <div className="form-actions" style={{ marginTop: '0.25rem' }}>
            <button type="button" className="ghost" onClick={downloadTemplate}>↓ Download template</button>
          </div>
          <div className="form-grid" style={{ marginTop: '0.75rem' }}>
            <div>
              <label className="form-label">CSV file</label>
              <input ref={fileInputRef} type="file" accept=".csv,text/csv" onChange={onFileChange} className="form-input" />
              {csvFilename && <p className="hint">{csvFilename} — {csvRows.length} valid row{csvRows.length === 1 ? '' : 's'}</p>}
            </div>
          </div>
          {csvParseErrors.length > 0 && (
            <ul className="error" style={{ marginTop: '0.5rem' }}>
              {csvParseErrors.map((e, i) => <li key={i}>{e}</li>)}
            </ul>
          )}
          {error && <p className="error">{error}</p>}
          <div className="form-actions">
            <button type="button" onClick={submitCsv} disabled={busy || csvRows.length === 0}>
              {busy ? 'Uploading…' : `Upload ${csvRows.length || ''} participant${csvRows.length === 1 ? '' : 's'}`}
            </button>
          </div>
        </div>
      )}

      {results && results.length > 0 && (
        <div style={{ marginTop: '1rem' }}>
          <h3 className="section-title" style={{ marginTop: 0 }}>Results</h3>
          <table className="participants-table">
            <thead>
              <tr><th>Username</th><th style={{ width: '11rem' }}>Status</th><th>Details</th></tr>
            </thead>
            <tbody>
              {results.map((r, i) => {
                const meta = STATUS_LABELS[r.status] || { label: r.status, cls: 'status-pill' };
                return (
                  <tr key={i}>
                    <td>{r.username}</td>
                    <td><span className={meta.cls}>{meta.label}</span></td>
                    <td>
                      {r.status === 'created' && r.temp_password && (
                        <>Temp password: <span className="mono">{r.temp_password}</span></>
                      )}
                      {r.status === 'error' && (r.reason || '—')}
                      {r.status === 'enrolled_existing' && 'Linked existing account.'}
                      {r.status === 'already_enrolled' && 'Was already in this session.'}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <p className="hint" style={{ marginTop: '0.5rem' }}>
            Share the temp passwords above with the new participants — they'll change them on first login.
          </p>
        </div>
      )}
    </div>
  );
}
